### ISSUE TITLE
Middleware to extend the headers

### ISSUE THREAD

**Issue by raphamorim** [davidB/axum-tracing-opentelemetry#12]
Hey there @davidB , great job with the project. I wonder if would make sense to add a feature to extend the headers in the current service, I know it already reads from the income request.

```rust
use axum_tracing_opentelemetry::propagate_headers_middleware;
```

```rust
        .layer(middleware::from_fn(propagate_headers_middleware))
        .layer(opentelemetry_tracing_layer())
```

> Following B3 pattern https://docs.rs/opentelemetry/0.9.1/i686-pc-windows-msvc/opentelemetry/sdk/propagation/struct.B3Propagator.html

```
   Client Tracer                                                  Server Tracer     
┌───────────────────────┐                                       ┌───────────────────────┐
│                       │                                       │                       │
│   TraceContext        │          Http Request Headers         │   TraceContext        │
│ ┌───────────────────┐ │         ┌───────────────────┐         │ ┌───────────────────┐ │
│ │ TraceId           │ │         │ X-B3-TraceId      │         │ │ TraceId           │ │
│ │                   │ │         │                   │         │ │                   │ │
│ │ ParentSpanId      │ │ Inject  │ X-B3-ParentSpanId │ Extract │ │ ParentSpanId      │ │
│ │                   ├─┼────────>│                   ├─────────┼>│                   │ │
│ │ SpanId            │ │         │ X-B3-SpanId       │         │ │ SpanId            │ │
│ │                   │ │         │                   │         │ │                   │ │
│ │ Sampling decision │ │         │ X-B3-Sampled      │         │ │ Sampling decision │ │
│ └───────────────────┘ │         └───────────────────┘         │ └───────────────────┘ │
│                       │                                       │                       │
└───────────────────────┘                                       └───────────────────────┘
```

> https://github.com/openzipkin/b3-propagation

Demo:

<img width="526" alt="Screenshot 2022-08-24 at 08 50 31" src="https://user-images.githubusercontent.com/3630346/186350296-c87b62be-5566-4603-9d01-c192f6fc140d.png">

Let me know if that make sense, I can definitely help with it.

**Comment by davidB** [comment]
Every PR are welcomes, but I don't understand the purpose.

1. in your code sample the propagate_headers_middleware is done after the tracing layer, so what is the purpose ?
2. In your diagram both client and server use TraceContext, why converting in B3 ?

FYI, the current extension extract the trace info from the incoming request (or create a new trace), those extracted info can be read for log but also to be injected to request to other service (queue, http request,...). As a sample in https://github.com/davidB/sandbox_axum_observability/blob/development/app/src/main.rs#L262 The TracingMiddleware for request inject the TraceContext.

**Comment by raphamorim** [comment]
Thanks for the response.

The purpose is inject [x-ot-span-context](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=forward_client_cert#x-ot-span-context), [x-b3-traceid](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=forward_client_cert#x-b3-traceid), [x-b3-spanid](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=forward_client_cert#x-b3-spanid), [x-b3-parentspanid](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=forward_client_cert#x-b3-parentspanid), [x-b3-sampled](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=forward_client_cert#x-b3-sampled), [x-b3-flags](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html?highlight=forward_client_cert#x-b3-flags) in the headers when necessary. 

> FYI, the current extension extract the trace info from the incoming request (or create a new trace), those extracted info can be read for log but also to be injected to request to other service (queue, http request,...). As a sample in https://github.com/davidB/sandbox_axum_observability/blob/development/app/src/main.rs#L262 The TracingMiddleware for request inject the TraceContext.

I see! I was able to inject the traceId on headers using the find_trace_id. Will give a shot using TraceContext. Thanks for the reply again.
