### ISSUE TITLE
Add convenience function to set trace-Id/span-Id

### ISSUE THREAD

**Issue by cschaible** [davidB/axum-tracing-opentelemetry#25]
In `tools/mod.rs` line 86 there is the convenience function `find_current_trace_id()` defined. This is nice to get the Trace-Id from from context (for the Span-Id is basically the same).

It would be nice to have a counterpart to set the Trace-Id and Span-Id from a string.
```
set_trace_id_in_context(trace_id: String) { ... }
```

My use-case is the following:
I send a message with kafka where i add the Trace-Id and Span-Id in b3-format in the message:
```
pub fn get_b3_trace_id() -> Option<String> {
    use opentelemetry::trace::TraceContextExt;
    use tracing_opentelemetry::OpenTelemetrySpanExt;
    let context = tracing::Span::current().context();
    let span = context.span();
    let span_context = span.span_context();

    let span_id = span_context
        .is_valid()
        .then(|| span_context.span_id().to_string());

    let trace_id = span_context
        .is_valid()
        .then(|| span_context.trace_id().to_string());

    if trace_id.is_none() || span_id.is_none() {
        None
    } else {
        // https://github.com/openzipkin/b3-propagation
        Some(format!("{}-{}-1", trace_id.unwrap(), span_id.unwrap()))
    }
}
```

On receiver side i have problems though to set the context correctly so all instrumented functions (with their spans) are tracked as children under the received Trace-Id.
I've tried different approaches but all implementations have the  problem that only the directly instrumented code block is mapped to the correct Trace-Id (i only see a span under the trace for the block where I call the `.instrument(span)`.

I use code similar to this:
```
let span = span!(Level::TRACE, "");
let context = get_context_from_b3(tracing_propagator.clone(), trace_id.to_string());
tracing_opentelemetry::OpenTelemetrySpanExt::set_parent(&span, context);
{
    ...
   // Problem: functions that are called here, that are annotated with #[instrument(name = "xyz"]
   // have a different Trace Id and are not correlated to the span that instruments the current block
}.instrument(span);


pub fn get_context_from_b3(propagator: Arc<Propagator>, b3_trace_id: String) -> Context {
    let mut extractor: HashMap<String, String> = HashMap::new();
    extractor.insert(B3_SINGLE_HEADER.to_string(), b3_trace_id);

    let context = propagator
        .extract_single_header(&extractor)
        .expect("Couldn't extract trace header");

    use opentelemetry::trace::TraceContextExt;

    Context::new().with_remote_span_context(context)
}
```

I would appreciate if you can provide a convenience function that simplifies setting the trace-id / (parent-)span-id or if you could explain how to solve it. 
Thanks in advance!

**Comment by davidB** [comment]
Hi,

Disclaimer: I'm not a tracing expert, and maybe I don't fully understand your issue.

Trace-id is not a mutable information.

My hypothesis is that your code block doesn't use the right parent span, aka calling `}.instrument(span)` is too late. Did you try to enter (activate the span) before your code block (see https://docs.rs/tracing/latest/tracing/span/index.html#entering-a-span) ?

Maybe something like
```rust
let span = span!(Level::TRACE, "");
let context = get_context_from_b3(tracing_propagator.clone(), trace_id.to_string());
tracing_opentelemetry::OpenTelemetrySpanExt::set_parent(&span, context);
span.in_scope(|| {

  // call other instrumented function
});
```

**Comment by cschaible** [comment]
Thank you for the hint to `enter` a span and the link to the documentation about `entering a span`.

`span.in_scope(|| {...})` doesn't work in my case as i have asynchronous code and according to the documentation only synchronous code should be put into the closure.

The documentation about entering a span though lead me to the `span.enter()` function [documentation](https://docs.rs/tracing/latest/tracing/struct.Span.html#method.enter). My use-case is there not 100% covered, but it lead my on the right path. I figured out that I have to `instrument` nested async function calls with the same span (I'm not sure if this is really the correct way to do it, but it works as intended).

The code looks like the following now:
```
let span = init_span_with_parent_from_kafka_message(kafka_message.headers(), tracing_propagator);
let _ = span.enter();
let _ = {
  //do something

  //Call nested async function that has #[instrument] attribute.
  //
  //It is not so nice, that the span has to be cloned, but at least it works as expected.
  //
  //Further instrumented nested functions that are called within "call_async_function" 
  //are correctly correlated to the parent span / trace-id without further adjustments.
  call_async_function(..).instrument(span.clone()).await;

  // do more things
}.instrument(span);
```

With this adjustment all nested spans are correctly sent to jaeger and displayed at the correct position.

The ticket can be closed as there is no further adjustment need in the library. Thanks again for your help!
