### ISSUE TITLE
Release for axum 0.6.0 release candidate? (MatchedPath not working)

### ISSUE THREAD

**Issue by fiadliel** [davidB/axum-tracing-opentelemetry#26]
It seems that when used with axum 0.6 release candidates, the `MatchedPath` isn't found (leading to not properly extracting `http.route`). Would it be possible to have an RC-release for 0.6?

You might want to wait for the actual release, in which case, this issue may help other people save on debugging time :)

**Comment by davidB** [comment]
Yes I planned to wait for release 0.6. But I can start working on it (and PR are welcome)

**Comment by fiadliel** [comment]
I could do a PR - I'm fairly new to rust, but see how it goes :)

Maybe it is premature though, without some decisions on how to support multiple versions / branching strategy / etc. Do you have opinions on how you'd want to do that? Or can I just push a bump to 0.6 on main branch?

**Comment by davidB** [comment]
Bump version to `0.6.0`
And add a compatibility table/note into README.
Maybe in the future, I'll switch to a features based approach to manage axum compatibility or not, I don't know yet :-P

Thanks

**Comment by davidB** [comment]
FIxe with the release 0.6 of the crate. (Need to include a compatibility table into the README)
