### ISSUE TITLE
Update / add new examples

### ISSUE THREAD

**Issue by TmLev** [davidB/axum-tracing-opentelemetry#29]
Hi!

I'm trying out this whole Prometheus/Tempo/OtelCollector setup, but it seems like the only example is a bit outdated (?).

Can you please update it? Or maybe add a new one?

**Comment by davidB** [comment]
Hi,

What issue do you have ?

I guess you talk about the sample under `examples/oltp`. There is an other "sample" at [davidB/sandbox_axum_observability: Sandbox to experiment axum and observability](https://github.com/davidB/sandbox_axum_observability) (rust code under `app/`).

**Comment by TmLev** [comment]
Yes, I was trying to reproduce https://github.com/davidB/sandbox_axum_observability.

I opened Grafana and it failed to load traces from Tempo:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/22966523/199939915-f5146423-3740-4f2f-84b3-f3441d745eff.png">

I'm not even sure whether app traces got send to Tempo/OtelCollector at all.

**Comment by davidB** [comment]
Ok you're right I forgot about the docker-compose sample, I mainly focus on the kubernetes one. I'll update it (PR are welcome also)

**Comment by davidB** [comment]
Finally I decided to remove the docker-compose examples, and only keep the
- docker with jaeger all-in-one (that now supports otlp)
- kubernetes (that I try to keep uptodate)
