### ISSUE TITLE
How to use it with existing tracer?

### ISSUE THREAD

**Issue by lcmgh** [davidB/axum-tracing-opentelemetry#44]
I am using the code example from https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/ to setup the regular tracing of my app. But my api calls are not being traced. What is wrong in my setup? I assume I do not need everything from `init_axum_tracer`.

```rust
pub fn init_axum_tracer() -> Result<sdktrace::Tracer, TraceError> {
    use axum_tracing_opentelemetry::{
        init_propagator, //stdio,
        resource::DetectResource,
        otlp,
    };

    let otel_rsrc = DetectResource::default()
        .with_fallback_service_name(env!("CARGO_PKG_NAME"))
        .with_fallback_service_version(env!("CARGO_PKG_VERSION"))
        .with_println()
        .build();
    let otel_tracer = otlp::init_tracer(otel_rsrc, otlp::identity)?;
    // to not send trace somewhere, but continue to create and propagate,...
    // then send them to `axum_tracing_opentelemetry::stdio::WriteNoWhere::default()`
    // or to `std::io::stdout()` to print
    //
    // let otel_tracer =
    //     stdio::init_tracer(otel_rsrc, stdio::identity, stdio::WriteNoWhere::default())?;
    init_propagator()?;

    Ok(otel_tracer)
}

let axum_tracer = init_axum_tracer().unwrap();

let tracer = init_tracer().unwrap();

tracing_subscriber::registry()
    .with(tracing_subscriber::EnvFilter::new(
        std::env::var("RUST_LOG").unwrap_or_else(|_| "amui=info,tower_http=info".into()),
    ))
    .with(tracing_subscriber::fmt::layer())
    .with(tracing_opentelemetry::layer().with_tracer(tracer))
    .init();
```

Router

```rust
..
        .layer(opentelemetry_tracing_layer())

```

**Comment by lcmgh** [comment]
My problem is when adding a second tracer the app crashes on startup.

```rust
let tracer = init_tracer().unwrap();

let axum_tracer = init_axum_tracer().unwrap();

tracing_subscriber::registry()
    .with(tracing_subscriber::EnvFilter::new(
        std::env::var("RUST_LOG").unwrap_or_else(|_| "amui=info".into()),
    ))
    .with(tracing_subscriber::fmt::layer())
    .with(tracing_opentelemetry::layer().with_tracer(tracer))
    .with(tracing_opentelemetry::layer().with_tracer(axum_tracer)) // no crash when removed but then I have no traces
    .init();
```

**Comment by lcmgh** [comment]
So my question is how would I add this lib to the `Kitchen Sink Configuration` outlined in here? https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/

**Comment by lcmgh** [comment]
> Basically, this library disables sampling by default, unless it's explicitly set in the parent span. So, you need to enable sampling for **all** requests in the tracer:

I indeed have enabled sampling for all requests.

**Comment by lcmgh** [comment]
I figured out I was missing this: axum_tracing_opentelemetry=info

```rust
let tracer = init_tracer().unwrap(); // from https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/

tracing_subscriber::registry()
.with(tracing_subscriber::EnvFilter::new(
    std::env::var("RUST_LOG").unwrap_or_else(|_| "amui=info,hyper=debug,axum_tracing_opentelemetry=info".into()),
))
.with(tracing_subscriber::fmt::layer())
.with(tracing_opentelemetry::layer().with_tracer(tracer))
.init();

```

**Comment by davidB** [comment]
@akeamc the librarie doesn't ignore the default sampling, but because trace are bind to tracing'span (the crate). The filtering is linked to tracing And if EnvFilter is setup, @lcmgh is right, axum_tracing_opentelemetry should be at least at info level (I'll update the README to clarify this point).

And about the sampling at opentelemetry itself, I let the default conf, but I plan to extend helper provided to create tracer to honor the environment variable [OTEL_TRACES_SAMPLER](https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_traces_sampler) (if not already supported by the opentelemetry crate).

**Comment by ttys3** [comment]
> I'm facing the same issue for all requests without trace id headers (`traceparent`, for example). Basically, this library disables sampling by default, unless it's explicitly set in the parent span. So, you need to enable sampling for **all** requests in the tracer:
> 
> ```rust
> let exporter = opentelemetry_otlp::new_exporter()
>   .tonic()
>   .with_endpoint(otlp_endpoint);
> 
> let tracer = opentelemetry_otlp::new_pipeline()
>   .tracing()
>   .with_exporter(exporter) 
>   .with_trace_config(trace::config().with_sampler(Sampler::AlwaysOn))
>   .install_batch(opentelemetry::runtime::Tokio)?;
> 
> // ...
> ```
> 
> I don't think the library should ignore the default sampling setting of the tracer. [`trace_extractor::create_context_with_trace`](https://github.com/davidB/axum-tracing-opentelemetry/blob/be392b207d7710c9f11c69e5bfcae42075dc6844/src/middleware/trace_extractor.rs#L224-L250) should probably look more similar to [how `actix-web-opentelemetry` does it](https://github.com/OutThereLabs/actix-web-opentelemetry/blob/cdce54efd2d26fe1b5eee3067220ffd80fea4483/src/middleware/trace.rs#L168-L170).

thank you very much.

`.with_trace_config(trace::config().with_sampler(Sampler::AlwaysOn))` did resolved my problem
