### ISSUE TITLE
Sampling traffic

### ISSUE THREAD

**Issue by samwalters3** [davidB/axum-tracing-opentelemetry#47]
I am looking to limit the tracing with just of 1% of all traffic, is there a solution that addresses that?

Thank you for the Work!

**Comment by davidB** [comment]
Hi,

I didn't test it myself, but you should be able define sampler by code (:
```
        let otel_rsrc = DetectResource::default()
            .with_fallback_service_name(env!("CARGO_PKG_NAME"))
            .with_fallback_service_version(env!("CARGO_PKG_VERSION"))
            .with_println()
            .build();
        let otel_tracer = otlp::init_tracer(otel_rsrc, |pipeline|{
          pipeline.with_trace_config(
            opentelemetry::sdk::trace::config()
                .with_resource(otel_rsrc)
                .with_sampler(Sampler::TraceIdRatioBased(0.01)),
          )
        })?;
```
(you can also replace init_tracer by your own code)

I don't know if the crate opentelemetry honors the env variable to define Sampling (curently init_tracer use AlwaysOn, but I'll add more support for env variable in coming version)

ref:
- [Sampler in opentelemetry::sdk::trace - Rust](https://docs.rs/opentelemetry/latest/opentelemetry/sdk/trace/enum.Sampler.html)
- [ShouldSample in opentelemetry::sdk::trace - Rust](https://docs.rs/opentelemetry/latest/opentelemetry/sdk/trace/trait.ShouldSample.html)
- [https://opentelemetry.io/docs/reference/specification/trace/sdk/#sampling](https://opentelemetry.io/docs/reference/specification/trace/sdk/#sampling)

**Comment by davidB** [comment]
with the version 0.10, you can define sampling via environment variable if you use the helper function.
