### ISSUE TITLE
Use valid operation / span name as display name for traces (in jaeger)

### ISSUE THREAD

**Issue by cschaible** [davidB/axum-tracing-opentelemetry#6]
At the moment all traces in jaeger's search result list seem to have the title `hello`.

This is most likely be caused by the code in [create_context_with_trace](https://github.com/davidB/axum-tracing-opentelemetry/blob/main/src/middleware.rs#L248).
```
let span = tracer.build_with_context(SpanBuilder::from_name("hello"), &remote_context);
```
The comments in the code indicate that the current implementation is only a hack / workaround.

I would expect to see something like the `HTTP-Method` and `route`  what seem to be the (display) values in the nested span (i.e. `/users/:identifier` from `http.route`).

It should be possible to pass the `name` (Line 145) or the `req` in line 137 to the `create_context_with_trace` function, to display the name instead of `hello`.

Even if the correct solution takes more time - would it be possible to release an improved version with a fix to display the values as suggested above?

**Comment by davidB** [comment]
Thanks for reporting, fix should part of 0.3.0
