### ISSUE TITLE
Custom log level

### ISSUE THREAD

**Issue by lcmgh** [davidB/axum-tracing-opentelemetry#64]
Hi! 

I have implemented a custom logger for all requests/responses. However calls that go through the `axum-tracing-opentelemetry` middleware also generate logs for my requests/responses (I guess because `span` also calls the `log` facade?). Is it possible to change the log level for those events or suppress them?

Thanks

**Comment by davidB** [comment]
No, every middleware should be able to log and create span (and depending on your subscriber, span'event creation, activation,... can also generate some log)
